### ISSUE TITLE
如何在vue3中扩展一个菜单按钮

### ISSUE THREAD

**Issue by ZhongChunle** [clinfc/wangeditor5-for-vue3#4]
## 需求描述
如何在vue3中扩展一个菜单按钮
描述你的需求详情
如何在vue3中扩展一个菜单按钮
## 需求功能点
点击插入附件按钮，实现插入附件功能
功能提要：
1、点击上传附件
2、上传成功回调后在当前上传的位置显示上传的文件，点击上传的附件可进行下载

## 参考或思路

可参考的产品或实现思路

**Comment by clinfc** [comment]
编辑器的功能扩展跟 vue 没有任何关系的，除非你想把上传部分的功能使用 vue 进行实现，我想你应该弄明白的是如何[扩展一个编辑器菜单](https://www.wangeditor.com/v5/development.html#buttonmenu)
