### ISSUE TITLE
支持word混合排版后，图片不显示

### ISSUE THREAD

**Issue by a152832** [clinfc/wangeditor5-for-vue3#5]
遇到的问题：复制word中的内容到富文本编辑器中，图片不显示

期望：制word中的内容到富文本编辑器中，显示图片

**Comment by clinfc** [comment]
这超出了本组件库的职责范围，请前往 wangEditor [官方仓库](https://github.com/wangeditor-team/wangEditor/issues) 提交 issues，或者参考 [此文章](https://juejin.cn/post/7024357194195795998) 进行实现
